version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - r3x-haskell-sdk-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Install executable
          command: stack install
      - save_cache:
          name: Cache Dependencies
          key: r3x-haskell-sdk-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - ".stack"
            - ".stack-work"
      - store_artifacts:
          path: ~/.local/bin/r3x-haskell-sdk-exe
          destination: r3x-haskell-sdk-exe

